CREATE TABLE NOTES (
  NOTE_ID INT NOT NULL AUTO_INCREMENT,
  NOTE_TITLE VARCHAR(100) NOT NULL,
  NOTE_CONTENT VARCHAR(4000) NOT NULL,
  NOTE_CREATION_DATE DATE,
  PRIMARY KEY (NOTE_ID)
);

CREATE TABLE CONTACTS (
  CONTACT_ID INT NOT NULL AUTO_INCREMENT,
  CONTACT_FORENAME VARCHAR(120) NOT NULL,
  CONTACT_SURNAME VARCHAR(120) NOT NULL,
  CONTACT_PHONE VARCHAR(15) NOT NULL,
  CONTACT_EMAIL VARCHAR(120) NOT NULL,
  PRIMARY KEY (CONTACT_ID)
);

CREATE TABLE APPOINTMENTS (
  APPOINTMENT_ID INT NOT NULL AUTO_INCREMENT,
  APPOINTMENT_TITLE VARCHAR(120) NOT NULL,
  APPOINTMENT_CATEGORY VARCHAR(120),
  APPOINTMENT_DESCRIPTION VARCHAR(120),
  APPOINTMENT_LOCATION VARCHAR(120),
  APPOINTMENT_DATE DATE,
  PRIMARY KEY (APPOINTMENT_ID)
);