-- Create a sample note
INSERT INTO NOTES
(NOTE_TITLE, NOTE_CONTENT, NOTE_CREATION_DATE)
VALUES
("Test title", "Test Note", NOW());

-- Create a sample contact
INSERT INTO CONTACTS
(CONTACT_FORENAME, CONTACT_SURNAME, CONTACT_PHONE, CONTACT_EMAIL)
VALUES
("Jack", "Evans", "07747502385", "jacK@evans.gb.net");

-- Create a sample appointment
INSERT INTO APPOINTMENTS
(APPOINTMENT_TITLE, APPOINTMENT_CATEGORY, APPOINTMENT_DESCRIPTION, APPOINTMENT_LOCATION, APPOINTMENT_DATE)
VALUES
("Maths Lecture", "Maths", "Really boring", "East Building", 02/08/2015);
